### ISSUE TITLE
Technical Documentation

### ISSUE THREAD

**Issue by intellisoftwaremx** [primeleaf/krystaldms-community-edition#7]
Is there any technical documentation available?

**Comment by rahulkubadia** [comment]
Not really, we just have source code and user and admin guide online. 

 

Regards,

Rahul Kubadia

+91 98211 61236

 

From: Maurice Stephen Villarreal ***@***.***> 
Sent: Saturday, March 11, 2023 12:33 AM
To: primeleaf/krystaldms-community-edition ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [primeleaf/krystaldms-community-edition] Technical Documentation (Issue #7)

 

Is there any technical documentation available?
